#!/usr/bin/env python3
"""Generate a static catalog page (docs/index.html) from data.json."""
import json, html, pathlib

TPL = """<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">
<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">
<title>Handy Chinese Software Catalog</title>
<meta name=\"description\" content=\"A small curated catalog of useful Chinese desktop tools.\">
<style>body{{font-family:system-ui,Segoe UI,Arial;max-width:820px;margin:40px auto;padding:0 16px;line-height:1.7;color:#222}}
.card{{border:1px solid #e5e5e5;border-radius:10px;padding:14px 16px;margin:12px 0}}
.cat{{color:#888;font-size:13px}} a{{color:#0066cc}}</style></head>
<body><h1>Handy Chinese Software Catalog</h1>
<p>A small, hand-curated list of useful Chinese desktop tools, generated from
<code>data.json</code> by a short Python script.</p>
{cards}
<p class=\"cat\">Generated by cn-software-catalog · MIT License</p></body></html>"""

CARD = '<div class="card"><h3><a href="{url}">{name}</a></h3>' \
       '<div class="cat">{cat}</div><p>{note}</p></div>'


def build():
    data = json.loads(pathlib.Path("data.json").read_text(encoding="utf-8"))
    cards = "\n".join(
        CARD.format(url=html.escape(d["url"]), name=html.escape(d["name"]),
                    cat=html.escape(d["cat"]), note=html.escape(d["note"]))
        for d in data)
    out = pathlib.Path("docs"); out.mkdir(exist_ok=True)
    (out / "index.html").write_text(TPL.format(cards=cards), encoding="utf-8")
    print(f"wrote docs/index.html with {len(data)} entries")


if __name__ == "__main__":
    build()
